"""Context assembly manager.

Assembles the optimal context window for each LLM query by combining
rolling transcript summaries, recent raw transcript, RAG-retrieved
document chunks, and optional web search results. Manages token budgets
to stay within model limits.

Phase 3 implementation.
"""

from __future__ import annotations

import asyncio
from datetime import datetime, timezone
from typing import Any

from app.context.raw_buffer import RawTranscriptBuffer
from app.context.rolling_summary import RollingSummary


class ContextManager:
    """Assembles and manages the context window for LLM queries.

    Combines multiple context sources (transcript, documents, search)
    into a single prompt that fits within the model's token budget.

    Attributes:
        max_context_tokens: Maximum tokens allocated for context.
        rolling_summary: The rolling transcript summarizer.
        raw_buffer: The raw transcript buffer.
        rag_pipeline: The RAG retrieval pipeline (``None`` until set).
    """

    def __init__(self, max_context_tokens: int = 8000) -> None:
        """Initialize the context manager and its sub-components.

        Args:
            max_context_tokens: Maximum number of tokens to allocate for
                context in each LLM query. Must leave room for the system
                prompt and model response.
        """
        self.max_context_tokens = max_context_tokens
        self.rolling_summary: RollingSummary = RollingSummary()
        self.raw_buffer: RawTranscriptBuffer = RawTranscriptBuffer(max_minutes=5)
        self.rag_pipeline: Any | None = None
        self.document_summaries: list[dict[str, str]] = []
        self._transcript_embed_buffer: list[tuple[datetime, str]] = []
        self._embed_chunk_target: int = 200  # words per RAG chunk
        self._embed_stale_seconds: float = 120.0  # force-flush if oldest entry > 2 min
        self._embed_lock = __import__('threading').Lock()

    def set_rag_pipeline(self, rag: Any) -> None:
        """Inject the RAG retrieval pipeline.

        Args:
            rag: An object with a ``search(query, top_k)`` method
                (e.g. :class:`~app.context.rag.RAGPipeline`).
        """
        self.rag_pipeline = rag

    def add_document_summary(self, filename: str, summary: str) -> None:
        """Register a document summary for inclusion in context.

        Args:
            filename: Display name of the document.
            summary: Full-document summary generated by the LLM.
        """
        if summary and summary.strip():
            self.document_summaries.append(
                {"filename": filename, "summary": summary}
            )

    # ------------------------------------------------------------------
    # Token helpers
    # ------------------------------------------------------------------

    def get_token_count(self, text: str) -> int:
        """Estimate the token count for a text string.

        Uses a fast word-based approximation (words x 1.3) rather than
        a full tokenizer, trading perfect accuracy for zero dependencies.

        Args:
            text: The text to count tokens for.

        Returns:
            Estimated token count.
        """
        return int(len(text.split()) * 1.3)

    # ------------------------------------------------------------------
    # Transcript ingestion
    # ------------------------------------------------------------------

    def add_transcript(self, text: str, timestamp: datetime | None = None) -> None:
        """Append new transcript text to the raw buffer and rolling summary.

        Before adding new text, collects entries about to be pruned from
        the raw buffer and embeds them into the RAG pipeline so old
        conversation chunks remain searchable.

        Args:
            text: Transcript text segment.
            timestamp: When the segment was captured. Defaults to now.
        """
        # Append to buffer — returns entries that just aged out
        pruned = self.raw_buffer.append(text, timestamp=timestamp)

        # Batch pruned entries into ~200-word chunks for RAG embedding
        if pruned and self.rag_pipeline is not None:
            with self._embed_lock:
                self._transcript_embed_buffer.extend(pruned)
                self._flush_embed_buffer()

        # RollingSummary.update is async. We schedule it on the running
        # loop when one exists; otherwise the pending text simply
        # accumulates and will be summarized on the next async call.
        try:
            loop = asyncio.get_running_loop()
            loop.create_task(self.rolling_summary.update(text))
        except RuntimeError:
            self.rolling_summary._pending_text += text

    # ------------------------------------------------------------------
    # Context assembly
    # ------------------------------------------------------------------

    def _flush_embed_buffer(self, force: bool = False) -> None:
        """Batch accumulated transcript lines into ~200-word chunks and embed.

        Accumulates short transcript lines until they reach the target
        chunk size, then embeds the combined text into RAG as a single
        paragraph-length chunk for better retrieval quality.

        Args:
            force: If True, embed whatever is buffered regardless of size.
        """
        if not self._transcript_embed_buffer or self.rag_pipeline is None:
            return

        # Combine all buffered lines
        combined = " ".join(text for _, text in self._transcript_embed_buffer)
        word_count = len(combined.split())

        # Force-flush if oldest entry has been sitting too long (> 2 min),
        # even if we haven't hit the 200-word target. Prevents transcript
        # from going invisible between the raw buffer and RAG.
        if not force and word_count < self._embed_chunk_target:
            oldest_ts = self._transcript_embed_buffer[0][0]
            age = (datetime.now(timezone.utc) - oldest_ts).total_seconds()
            if age < self._embed_stale_seconds:
                return  # wait for more lines
            force = True  # stale — flush what we have

        # Embed in ~200-word chunks with 10% overlap
        words = combined.split()
        overlap = self._embed_chunk_target // 10
        start = 0

        while start < len(words):
            end = min(start + self._embed_chunk_target, len(words))
            chunk_text = " ".join(words[start:end])

            min_words = 5 if force else 20
            if len(chunk_text.split()) >= min_words:
                first_ts = self._transcript_embed_buffer[0][0]
                last_ts = self._transcript_embed_buffer[-1][0]
                try:
                    self.rag_pipeline.add_chunk(
                        text=chunk_text,
                        metadata={
                            "source": "meeting_transcript",
                            "start_time": first_ts.isoformat(),
                            "end_time": last_ts.isoformat(),
                        },
                    )
                except Exception as exc:
                    import logging
                    logging.getLogger(__name__).warning("Failed to embed transcript chunk: %s", exc)

            if end >= len(words):
                break
            start = end - overlap

        self._transcript_embed_buffer.clear()

    def _truncate_from_beginning(self, text: str, max_tokens: int) -> str:
        """Truncate *text* from the beginning to fit within *max_tokens*.

        Keeps the most recent content (end of string) which is typically
        the most relevant for meeting context.

        Args:
            text: The source text.
            max_tokens: Token budget for this section.

        Returns:
            The (possibly truncated) text.
        """
        words = text.split()
        # Reverse the approximation: max_tokens / 1.3 ~ max_words
        max_words = int(max_tokens / 1.3)
        if len(words) <= max_words:
            return text
        return " ".join(words[-max_words:])

    def assemble_context(self, question: str, session_id: str) -> str:
        """Build the full context string for an LLM query.

        Assembles context in priority order:
        1. Rolling summary of the full conversation
        2. Recent raw transcript (last ~5 minutes)
        3. RAG-retrieved document chunks relevant to the question

        Token budget allocation (approximate):
        - 20 % meeting summary
        - 30 % recent buffer
        - 20 % document summaries (full-document understanding)
        - 30 % RAG chunks (specific document passages)

        Args:
            question: The user's question, used to guide RAG retrieval.
            session_id: The active meeting session ID for retrieving
                the correct transcript data.

        Returns:
            A formatted context string ready for inclusion in the
            LLM prompt, within the token budget.
        """
        budget_summary = int(self.max_context_tokens * 0.20)
        budget_buffer = int(self.max_context_tokens * 0.30)
        budget_doc_summaries = int(self.max_context_tokens * 0.20)
        budget_rag = int(self.max_context_tokens * 0.30)

        # --- Section 1: Rolling meeting summary ---
        summary_text = self.rolling_summary.get_summary()
        summary_text = self._truncate_from_beginning(summary_text, budget_summary)

        # --- Section 2: Recent raw transcript ---
        recent_text = self.raw_buffer.get_recent(minutes=5)
        recent_text = self._truncate_from_beginning(recent_text, budget_buffer)

        # --- Section 3: Document summaries (full-document understanding) ---
        doc_summary_text = ""
        if self.document_summaries:
            parts = []
            for doc in self.document_summaries:
                parts.append(f"[{doc['filename']}]:\n{doc['summary']}")
            doc_summary_text = "\n\n".join(parts)
        doc_summary_text = self._truncate_from_beginning(
            doc_summary_text, budget_doc_summaries
        )

        # --- Section 4: RAG chunks (specific passages) ---
        # Flush any pending transcript into RAG before searching,
        # so recently-pruned content is findable immediately.
        if self.rag_pipeline is not None:
            with self._embed_lock:
                self._flush_embed_buffer(force=True)

        rag_text = ""
        if self.rag_pipeline is not None:
            try:
                results: list[dict[str, Any]] = self.rag_pipeline.search(
                    query=question, top_k=8
                )
                chunks: list[str] = []
                for result in results:
                    text_content = result.get("text", "")
                    metadata = result.get("metadata", {})
                    if metadata.get("source") == "meeting_transcript":
                        label = "Earlier in this meeting"
                    else:
                        label = metadata.get("filename", "document")
                    chunks.append(f"[{label}]: {text_content}")
                rag_text = "\n\n".join(chunks)
            except Exception:
                rag_text = ""

        rag_text = self._truncate_from_beginning(rag_text, budget_rag)

        # --- Assemble (skip empty sections to avoid confusing the LLM) ---
        sections: list[str] = []

        if summary_text.strip():
            sections.append("=== MEETING SUMMARY ===")
            sections.append(summary_text)
            sections.append("")

        if recent_text.strip():
            sections.append("=== RECENT CONVERSATION (last 5 minutes) ===")
            sections.append(recent_text)
            sections.append("")

        if doc_summary_text.strip():
            sections.append("=== DOCUMENT OVERVIEWS ===")
            sections.append(doc_summary_text)
            sections.append("")

        if rag_text.strip():
            sections.append("=== RELEVANT DOCUMENT PASSAGES ===")
            sections.append(rag_text)

        if not sections:
            return "(Meeting just started — no context available yet.)"

        return "\n".join(sections)

    # ------------------------------------------------------------------
    # Reset
    # ------------------------------------------------------------------

    def flush_remaining_embeddings(self) -> None:
        """Flush all transcript into RAG — including entries still in the raw buffer.

        Called at meeting end. Drains the raw buffer so that the final
        ~5 minutes of conversation are also embedded, not just the
        entries that had already aged out of the buffer window.
        """
        with self._embed_lock:
            # Drain everything still in the raw buffer into the embed buffer
            with self.raw_buffer._lock:
                remaining = list(self.raw_buffer._entries)
            if remaining and self.rag_pipeline is not None:
                self._transcript_embed_buffer.extend(remaining)
            self._flush_embed_buffer(force=True)

    def reset(self) -> None:
        """Clear all context layers.

        Used when resetting between sessions or when the meeting ends.
        Flushes any remaining transcript lines into RAG before clearing.
        """
        with self._embed_lock:
            self._flush_embed_buffer(force=True)
        self.rolling_summary.reset()
        self.raw_buffer.clear()
        self.rag_pipeline = None
        self.document_summaries.clear()
