"""Context assembly manager.

Assembles the optimal context window for each LLM query by combining
rolling transcript summaries, recent raw transcript, RAG-retrieved
document chunks, and optional web search results. Manages token budgets
to stay within model limits.

Phase 3 implementation.
"""

from __future__ import annotations

import asyncio
import logging
import re
import threading
from datetime import datetime, timezone
from typing import Any

from app.context.raw_buffer import RawTranscriptBuffer
from app.context.rolling_summary import RollingSummary

logger = logging.getLogger(__name__)

# Markers for entity extraction
_DECISION_MARKERS = (
    "we decided", "let's go with", "agreed to", "the decision is",
    "we'll do", "final answer is",
)
_ACTION_MARKERS = (
    "i will", "i'll", "we need to", "action item", "todo",
    "follow up on", "assigned to",
)
_VAGUE_PRONOUNS = {"he", "she", "they", "that", "this", "it", "their", "them", "its", "his", "her"}
_SKIP_WORDS = _VAGUE_PRONOUNS | {
    "about", "would", "could", "should", "think", "really",
    "there", "where", "which", "these", "those", "going",
    "great", "right", "being", "other", "still", "after",
    "before", "between", "under", "above",
}


class ContextManager:
    """Assembles and manages the context window for LLM queries.

    Combines multiple context sources (transcript, documents, search)
    into a single prompt that fits within the model's token budget.

    Attributes:
        max_context_tokens: Maximum tokens allocated for context.
        rolling_summary: The rolling transcript summarizer.
        raw_buffer: The raw transcript buffer.
        rag_pipeline: The RAG retrieval pipeline (``None`` until set).
    """

    # Maximum number of screen content entries to retain.
    _MAX_SCREEN_ENTRIES: int = 30

    def __init__(
        self,
        max_context_tokens: int = 16000,
        meeting_id: str = "",
        agent_id: str = "",
        user_id: str = "",
    ) -> None:
        """Initialize the context manager and its sub-components.

        Args:
            max_context_tokens: Maximum number of tokens to allocate for
                context in each LLM query. Must leave room for the system
                prompt and model response.
            meeting_id: Unique meeting identifier for scope isolation.
            agent_id: Agent identifier for scope isolation.
            user_id: User identifier for scope isolation.
        """
        self.max_context_tokens = max_context_tokens
        self.meeting_id = meeting_id
        self.agent_id = agent_id
        self.user_id = user_id
        self.rolling_summary: RollingSummary = RollingSummary()
        self.raw_buffer: RawTranscriptBuffer = RawTranscriptBuffer(max_minutes=10)
        self.rag_pipeline: Any | None = None
        self.document_summaries: list[dict[str, str]] = []
        self.past_meeting_summaries: list[dict[str, str]] = []
        self._entities: dict[str, set[str]] = {
            "people": set(),
            "topics": set(),
            "decisions": set(),
            "action_items": set(),
        }
        self._transcript_embed_buffer: list[tuple[datetime, str]] = []
        self._embed_chunk_target: int = 200  # words per RAG chunk
        self._embed_stale_seconds: float = 120.0  # force-flush if oldest entry > 2 min
        self._embed_lock = threading.Lock()
        self._embed_failed_chunks: list[tuple[str, dict[str, str]]] = []
        self._embed_retry_count: int = 0
        self._screen_contents: list[str] = []
        # tiktoken tokenizer for accurate token budgeting
        self._tokenizer = None
        try:
            import tiktoken
            self._tokenizer = tiktoken.get_encoding("cl100k_base")
        except Exception:
            pass  # fallback to word * 1.5 approximation
        # Lock protecting shared state read by assemble_context (run in thread
        # executor) and mutated by add_transcript / add_document_summary / etc.
        # on the event loop. Covers: document_summaries, past_meeting_summaries,
        # _entities.
        self._state_lock = threading.Lock()

    def set_rag_pipeline(self, rag: Any) -> None:
        """Inject the RAG retrieval pipeline.

        Args:
            rag: An object with a ``search(query, top_k)`` method
                (e.g. :class:`~app.context.rag.RAGPipeline`).
        """
        self.rag_pipeline = rag

    def add_document_summary(self, filename: str, summary: str) -> None:
        """Register a document summary for inclusion in context.

        Args:
            filename: Display name of the document.
            summary: Full-document summary generated by the LLM.
        """
        if summary and summary.strip():
            with self._state_lock:
                self.document_summaries.append(
                    {"filename": filename, "summary": summary}
                )

    def add_screen_content(self, content: str) -> None:
        """Register extracted screen content for inclusion in context.

        Retains only the most recent _MAX_SCREEN_ENTRIES entries to
        prevent unbounded memory growth during long meetings.

        Args:
            content: Text extracted from the shared screen by Gemini Vision.
        """
        if content and content.strip():
            self._screen_contents.append(content.strip())
            if len(self._screen_contents) > self._MAX_SCREEN_ENTRIES:
                self._screen_contents.pop(0)

    def add_past_meeting_summary(self, meeting_date: str, summary: str) -> None:
        """Register a past meeting summary for cross-meeting memory.

        Args:
            meeting_date: ISO date or display string for the meeting.
            summary: Summary text from the previous meeting.
        """
        if summary and summary.strip():
            with self._state_lock:
                self.past_meeting_summaries.append(
                    {"meeting_date": meeting_date, "summary": summary.strip()}
                )

    def _extract_entities(self, text: str, speaker: str = "") -> None:
        """Extract named entities and key phrases from transcript text.

        Detects decisions, action items, and tracks speakers as people.
        Thread-safe: acquires ``_state_lock`` for all entity mutations.

        Args:
            text: Transcript text to analyze.
            speaker: Speaker name (added to people set).
        """
        text_lower = text.lower()

        with self._state_lock:
            if speaker and speaker.strip():
                self._entities["people"].add(speaker.strip())

            for marker in _DECISION_MARKERS:
                if marker in text_lower:
                    idx = text_lower.index(marker)
                    end = text.find(".", idx)
                    if end == -1:
                        end = len(text)
                    decision = text[idx:end + 1].strip()
                    if len(decision) > 10:
                        self._entities["decisions"].add(decision)
                    break

            for marker in _ACTION_MARKERS:
                if marker in text_lower:
                    idx = text_lower.index(marker)
                    end = text.find(".", idx)
                    if end == -1:
                        end = len(text)
                    action = text[idx:end + 1].strip()
                    if len(action) > 10:
                        self._entities["action_items"].add(action)
                    break

    def _rewrite_query(self, question: str, recent_text: str) -> str:
        """Expand questions with recent conversation context.

        Handles two cases:
        1. Vague pronouns (he/she/they/their) — resolved to specific names
        2. Short follow-up questions missing topic context — expanded with
           recent key topics so RAG and web search find relevant results.

        Example: After discussing restaurants in India, the follow-up
        "give me good locations in Delhi" becomes
        "give me good locations in Delhi (context: restaurant India)"

        Args:
            question: The raw user question.
            recent_text: Recent transcript buffer text for context.

        Returns:
            The expanded query, or the original if no expansion needed.
        """
        words = question.lower().split()

        # Always try to add topic context for short-to-medium questions
        # (up to 10 words) when recent conversation exists
        if len(words) >= 10:
            return question

        has_vague = any(w in _VAGUE_PRONOUNS for w in words)

        # Build expansion from recent context
        expansions: list[str] = []

        if recent_text:
            # Extract key topics from the last 5 lines of buffer
            # (both speaker and bot responses for full context)
            lines = recent_text.strip().split("\n")[-5:]
            for line in lines:
                if ": " in line:
                    content = line.split(": ", 1)[1]
                else:
                    content = line
                # Remove type tags like [QUESTION] [DECISION]
                content = re.sub(r"\[(?:QUESTION|DECISION|ACTION)\]\s*", "", content)
                for w in content.split():
                    cleaned = re.sub(r"[^\w]", "", w)
                    if len(cleaned) > 4 and cleaned.lower() not in _SKIP_WORDS:
                        if cleaned not in expansions:
                            expansions.append(cleaned)

            # Also add speaker names for pronoun resolution
            if has_vague:
                seen_speakers: list[str] = []
                for line in reversed(recent_text.strip().split("\n")):
                    if ": " in line:
                        speaker_part = line.split(": ", 1)[0]
                        if "] " in speaker_part:
                            speaker_part = speaker_part.rsplit("] ", 1)[-1]
                        speaker_part = speaker_part.strip()
                        if speaker_part and speaker_part not in seen_speakers:
                            seen_speakers.append(speaker_part)
                        if len(seen_speakers) >= 3:
                            break
                if seen_speakers:
                    expansions = seen_speakers + expansions

        if expansions:
            expansion = " ".join(expansions[:10])
            return f"{question} (context: {expansion})"
        return question

    # ------------------------------------------------------------------
    # Token helpers
    # ------------------------------------------------------------------

    def get_token_count(self, text: str) -> int:
        """Count tokens using tiktoken for accurate prompt budgeting.

        Falls back to a word-based approximation (words x 1.5) if
        tiktoken is unavailable.

        Args:
            text: The text to count tokens for.

        Returns:
            Token count.
        """
        if self._tokenizer is not None:
            return len(self._tokenizer.encode(text, disallowed_special=()))
        return int(len(text.split()) * 1.5)

    # ------------------------------------------------------------------
    # Transcript ingestion
    # ------------------------------------------------------------------

    def add_transcript(self, text: str, timestamp: datetime | None = None) -> None:
        """Append new transcript text to the raw buffer and rolling summary.

        Collects entries evicted from the raw buffer (both deque overflow
        and time-based pruning) and routes them to the embed buffer so
        they end up in ChromaDB rather than being silently lost.

        Args:
            text: Transcript text segment.
            timestamp: When the segment was captured. Defaults to now.
        """
        # Extract entities from transcript (speaker detection from "Speaker: text" format)
        speaker = ""
        if ": " in text:
            speaker = text.split(": ", 1)[0].strip()
        self._extract_entities(text, speaker)

        # Append to buffer — returns entries evicted by overflow or age
        evicted = self.raw_buffer.append(text, timestamp=timestamp)

        # Route evicted entries into the embed buffer for RAG embedding
        if evicted and self.rag_pipeline is not None:
            with self._embed_lock:
                self._transcript_embed_buffer.extend(evicted)
            self._flush_embed_buffer()

        # RollingSummary.update is async. We schedule it on the running
        # loop when one exists; otherwise the pending text accumulates.
        # We also drain pending text when a loop IS available to prevent
        # unbounded growth from earlier sync-context ingestion.
        try:
            loop = asyncio.get_running_loop()
            task = loop.create_task(self.rolling_summary.update(text))
            task.add_done_callback(
                lambda t: logger.error("Summary update failed: %s", t.exception())
                if not t.cancelled() and t.exception() else None
            )
        except RuntimeError:
            self.rolling_summary.add_pending(text)

    # ------------------------------------------------------------------
    # Context assembly
    # ------------------------------------------------------------------

    def _flush_embed_buffer(self, force: bool = False) -> None:
        """Batch accumulated transcript lines into ~200-word chunks and embed.

        Accumulates short transcript lines until they reach the target
        chunk size, then embeds the combined text into RAG as a single
        paragraph-length chunk for better retrieval quality.

        Extracts data under the embed lock, then releases it before the
        actual encoding call (which is slow) to avoid blocking other
        callers.

        Args:
            force: If True, embed whatever is buffered regardless of size.
        """
        # Check state under lock, then release before slow encoding work
        with self._embed_lock:
            if self.rag_pipeline is None:
                return
            has_pending = bool(self._transcript_embed_buffer)
            has_failed = bool(self._embed_failed_chunks)

        if not has_pending and not has_failed:
            return
        if not has_pending:
            self._retry_failed_embeds()
            return

        with self._embed_lock:
            # Check whether we should flush yet
            combined = " ".join(text for _, text in self._transcript_embed_buffer)
            word_count = len(combined.split())

            if not force and word_count < self._embed_chunk_target:
                oldest_ts = self._transcript_embed_buffer[0][0]
                age = (datetime.now(timezone.utc) - oldest_ts).total_seconds()
                if age < self._embed_stale_seconds:
                    return  # wait for more lines
                force = True  # stale — flush what we have

            # Copy the buffer and clear it while still under lock
            buffer_copy = list(self._transcript_embed_buffer)
            self._transcript_embed_buffer.clear()

        # Build a word-to-entry index for accurate per-chunk timestamps.
        # Each word maps back to the entry it came from, so chunks get
        # the timestamp of their first and last contributing entry.
        entry_words: list[tuple[str, int]] = []  # (word, entry_index)
        for idx, (_, text) in enumerate(buffer_copy):
            for w in text.split():
                entry_words.append((w, idx))

        # Embed in ~200-word chunks with 10% overlap (outside the lock)
        overlap = self._embed_chunk_target // 10
        start = 0

        while start < len(entry_words):
            end = min(start + self._embed_chunk_target, len(entry_words))
            chunk_words = entry_words[start:end]
            chunk_text = " ".join(w for w, _ in chunk_words)

            min_words = 5 if force else 20
            if len(chunk_words) >= min_words:
                first_entry_idx = chunk_words[0][1]
                last_entry_idx = chunk_words[-1][1]
                first_ts = buffer_copy[first_entry_idx][0]
                last_ts = buffer_copy[last_entry_idx][0]
                # Extract unique speakers from the chunk entries
                chunk_entry_indices = set(idx for _, idx in chunk_words)
                speakers_in_chunk = set()
                for ei in chunk_entry_indices:
                    entry_text = buffer_copy[ei][1]
                    # Speaker is the part before first ": "
                    if ": " in entry_text:
                        spk = entry_text.split(": ", 1)[0].strip()
                        if spk:
                            speakers_in_chunk.add(spk)

                chunk_metadata = {
                    "source_type": "transcript",
                    "source": "meeting_transcript",
                    "meeting_id": self.meeting_id,
                    "agent_id": self.agent_id,
                    "user_id": self.user_id,
                    "speakers": ", ".join(sorted(speakers_in_chunk)) or "unknown",
                    "start_time": first_ts.isoformat(),
                    "end_time": last_ts.isoformat(),
                }
                try:
                    self.rag_pipeline.add_chunk(
                        text=chunk_text,
                        metadata=chunk_metadata,
                    )
                except Exception as exc:
                    logger.warning("Failed to embed transcript chunk: %s — queued for retry", exc)
                    self._embed_failed_chunks.append((chunk_text, chunk_metadata))

            if end >= len(entry_words):
                break
            start = end - overlap

        self._retry_failed_embeds()

    def _retry_failed_embeds(self) -> None:
        """Retry embedding chunks that failed on previous flush attempts.

        Snapshots the failed list under lock, retries outside the lock
        (slow IO), then merges results back under lock. Drops remaining
        chunks after 3 consecutive cycles with zero progress.
        """
        if self.rag_pipeline is None:
            return

        with self._embed_lock:
            if not self._embed_failed_chunks:
                return
            chunks_to_retry = list(self._embed_failed_chunks)

        # Retry outside the lock — add_chunk may be slow
        still_failed: list[tuple[str, dict[str, str]]] = []
        succeeded = 0
        for chunk_text_retry, chunk_meta_retry in chunks_to_retry:
            try:
                self.rag_pipeline.add_chunk(text=chunk_text_retry, metadata=chunk_meta_retry)
                succeeded += 1
            except Exception:
                still_failed.append((chunk_text_retry, chunk_meta_retry))

        if succeeded:
            logger.info("Retried %d failed embed chunks successfully", succeeded)

        # Merge back under lock — preserve any new failures added concurrently
        with self._embed_lock:
            # Remove retried items from the live list, keep new ones
            retried_set = set(id(c) for c in chunks_to_retry)
            new_failures = [c for c in self._embed_failed_chunks if id(c) not in retried_set]
            self._embed_failed_chunks = new_failures + still_failed

            if still_failed and succeeded == 0:
                self._embed_retry_count += 1
                if self._embed_retry_count >= 3:
                    logger.error(
                        "Dropping %d embed chunks after 3 retry cycles with no progress",
                        len(still_failed),
                    )
                    self._embed_failed_chunks = [c for c in self._embed_failed_chunks if c not in still_failed]
                    self._embed_retry_count = 0
            else:
                self._embed_retry_count = 0

    def _truncate_from_end(self, text: str, max_tokens: int) -> str:
        """Truncate *text* from the end to fit within *max_tokens*.

        Keeps the beginning of the text which is typically the most
        relevant for RAG chunks and document summaries (key information
        tends to appear at the start).

        Args:
            text: The source text.
            max_tokens: Token budget for this section.

        Returns:
            The (possibly truncated) text.
        """
        if self.get_token_count(text) <= max_tokens:
            return text
        words = text.split()
        lo, hi = 0, len(words)
        while lo < hi:
            mid = (lo + hi + 1) // 2
            candidate = " ".join(words[:mid])
            if self.get_token_count(candidate) <= max_tokens:
                lo = mid
            else:
                hi = mid - 1
        return " ".join(words[:lo]) + "..." if lo > 0 else ""

    def _truncate_from_beginning(self, text: str, max_tokens: int) -> str:
        """Truncate *text* from the beginning to fit within *max_tokens*.

        Keeps the most recent content (end of string) which is typically
        the most relevant for meeting context. Uses tiktoken for accurate
        token counting when available.

        Args:
            text: The source text.
            max_tokens: Token budget for this section.

        Returns:
            The (possibly truncated) text.
        """
        if self.get_token_count(text) <= max_tokens:
            return text
        # Binary search for the right number of words from the end
        words = text.split()
        lo, hi = 0, len(words)
        while lo < hi:
            mid = (lo + hi + 1) // 2
            candidate = " ".join(words[-mid:])
            if self.get_token_count(candidate) <= max_tokens:
                lo = mid
            else:
                hi = mid - 1
        return " ".join(words[-lo:]) if lo > 0 else ""

    def assemble_context(self, question: str, session_id: str) -> str:
        """Build the full context string for an LLM query.

        Section order is optimized for Gemini implicit prompt caching:
        stable content that does not change within a meeting sits at the
        top (cacheable prefix), dynamic content sits below the LIVE
        CONTEXT marker.

        STABLE (cacheable prefix):
        0. Past meeting summaries (cross-meeting memory) — fixed on meeting start
        1. Document overviews (full-document understanding) — uploaded pre-meeting

        DYNAMIC (changes during the meeting):
        2. Rolling summary of the conversation — updates every ~60 s
        3. Tracked entities (people, decisions, action items)
        4. Recent raw transcript (last ~10 minutes) — new every line
        5. Shared screen content (Gemini-extracted from screenshare frames)
        6. RAG-retrieved chunks (specific passages) — PRIMARY SOURCE, per-question

        Token budget allocation (approximate):
        - 10 % past meeting summaries
        - 10 % document summaries
        - 15 % rolling summary
        - 25 % recent buffer
        - 20 % shared screen content
        - 20 % RAG chunks

        Args:
            question: The user's question, used to guide RAG retrieval.
            session_id: The active meeting session ID for retrieving
                the correct transcript data.

        Returns:
            A formatted context string ready for inclusion in the
            LLM prompt, within the token budget.
        """
        budget_past = int(self.max_context_tokens * 0.10)
        budget_summary = int(self.max_context_tokens * 0.15)
        budget_buffer = int(self.max_context_tokens * 0.25)
        budget_doc_summaries = int(self.max_context_tokens * 0.10)
        budget_screen = int(self.max_context_tokens * 0.20)
        budget_rag = int(self.max_context_tokens * 0.20)

        # Snapshot shared state under lock (this method runs in a thread
        # executor while the event loop mutates these collections).
        with self._state_lock:
            past_summaries_snap = list(self.past_meeting_summaries)
            doc_summaries_snap = list(self.document_summaries)
            entities_snap = {k: set(v) for k, v in self._entities.items()}

        # --- Section 0: Past meeting summaries (cross-meeting memory) ---
        past_text = ""
        if past_summaries_snap:
            parts = []
            for past in past_summaries_snap:
                parts.append(f"[{past['meeting_date']}]:\n{past['summary']}")
            past_text = "\n\n".join(parts)
        past_text = self._truncate_from_beginning(past_text, budget_past)

        # --- Section 1: Rolling meeting summary ---
        # Note: get_summary() appends unsummarized pending text automatically
        summary_text = self.rolling_summary.get_summary()
        summary_text = self._truncate_from_beginning(summary_text, budget_summary)

        # --- Section 2: Recent raw transcript ---
        recent_text = self.raw_buffer.get_recent(minutes=10)
        recent_text = self._truncate_from_beginning(recent_text, budget_buffer)

        # --- Section 3: Document summaries (full-document understanding) ---
        doc_summary_text = ""
        if doc_summaries_snap:
            parts = []
            for doc in doc_summaries_snap:
                parts.append(f"[{doc['filename']}]:\n{doc['summary']}")
            doc_summary_text = "\n\n".join(parts)
        doc_summary_text = self._truncate_from_end(
            doc_summary_text, budget_doc_summaries
        )

        # --- Section 5: RAG chunks (specific passages) — computed before screen but output after ---
        # Flush any pending transcript into RAG before searching,
        # so recently-pruned content is findable immediately.
        if self.rag_pipeline is not None:
            self._flush_embed_buffer(force=True)

        rag_text = ""
        if self.rag_pipeline is not None:
            expanded_query = self._rewrite_query(question, recent_text)
            search_fn = (
                self.rag_pipeline.hybrid_search
                if hasattr(self.rag_pipeline, "hybrid_search")
                else self.rag_pipeline.search
            )

            # Separate queries for transcript and documents (Item 4).
            # Supports both legacy metadata (source: "document") and new
            # metadata (source_type: "document") for backward compat.
            transcript_chunks: list[str] = []
            document_chunks: list[str] = []
            seen_prefixes: set[str] = set()

            def _dedup_add(target: list[str], label: str, text: str) -> None:
                prefix = text[:100]
                if prefix not in seen_prefixes:
                    seen_prefixes.add(prefix)
                    target.append(f"[{label}]: {text}")

            try:
                # Current meeting transcript (highest priority)
                if self.meeting_id:
                    try:
                        current_results = search_fn(
                            query=expanded_query, top_k=4,
                            where={"meeting_id": self.meeting_id},
                        )
                    except Exception:
                        current_results = []
                    for r in current_results:
                        meta = r.get("metadata", {})
                        ts = meta.get("start_time", "")
                        speakers = meta.get("speakers", "unknown")
                        label = f"This meeting ({speakers}, {ts[:16]})" if ts else f"This meeting ({speakers})"
                        _dedup_add(transcript_chunks, label, r["text"])

                # Archived transcript — try source_type first, fall back to source
                for filt in ({"source_type": "transcript"}, {"source": "meeting_transcript"}):
                    try:
                        archived_results = search_fn(
                            query=expanded_query, top_k=4, where=filt,
                        )
                    except Exception:
                        archived_results = []
                    for r in archived_results:
                        meta = r.get("metadata", {})
                        mid = meta.get("meeting_id", "")
                        if mid == self.meeting_id:
                            continue
                        ts = meta.get("start_time", "")
                        label = f"Earlier meeting ({ts[:10]})" if ts else "Earlier meeting"
                        _dedup_add(transcript_chunks, label, r["text"])
            except Exception:
                pass

            try:
                # Document chunks — try source_type first, fall back to source
                for filt in ({"source_type": "document"}, {"source": "document"}):
                    try:
                        doc_results = search_fn(
                            query=expanded_query, top_k=4, where=filt,
                        )
                    except Exception:
                        doc_results = []
                    for r in doc_results:
                        meta = r.get("metadata", {})
                        fname = meta.get("filename", "document")
                        chunk_idx = meta.get("chunk_index", "")
                        page = meta.get("page_number", "")
                        provenance = fname
                        if page:
                            provenance += f", p.{page}"
                        elif chunk_idx != "":
                            provenance += f", chunk {chunk_idx}"
                        _dedup_add(document_chunks, provenance, r["text"])
            except Exception:
                pass

            all_chunks = transcript_chunks + document_chunks
            rag_text = "\n\n".join(all_chunks)

        rag_text = self._truncate_from_end(rag_text, budget_rag)

        # --- Section 4: Shared screen content ---
        screen_text = ""
        if self._screen_contents:
            # Walk from the end (most recent) accumulating until budget is reached,
            # avoiding constructing the full string only to truncate most of it.
            max_words = int(budget_screen / 1.3)
            parts: list[str] = []
            word_count = 0
            for entry in reversed(self._screen_contents):
                entry_words = len(entry.split())
                if word_count + entry_words > max_words:
                    break
                parts.append(entry)
                word_count += entry_words
            if parts:
                screen_text = "\n\n---\n\n".join(reversed(parts))

        # --- Assemble (skip empty sections to avoid confusing the LLM) ---
        #
        # Section order matters for Gemini implicit prompt caching: anything
        # byte-identical across successive calls within a meeting sits at the
        # TOP so it can be cached; anything that changes per-line or per-
        # question sits BELOW the DYNAMIC marker.
        #
        # Stable (cacheable): past meetings, document overviews.
        # Dynamic: rolling summary (changes ~60s), tracked entities (new
        #   people/decisions/actions), shared screen, recent transcript
        #   (every new line), RAG hits (per-question).
        sections: list[str] = []

        # ---------------- STABLE BLOCK (cacheable prefix) ----------------
        if past_text.strip():
            sections.append("=== PAST MEETINGS ===")
            sections.append(past_text)
            sections.append("")

        if doc_summary_text.strip():
            sections.append("=== DOCUMENT OVERVIEWS ===")
            sections.append(doc_summary_text)
            sections.append("")

        # ---------------- DYNAMIC BLOCK (changes during meeting) ---------
        # Entities section — give the LLM quick reference to tracked items
        entity_parts: list[str] = []
        if entities_snap["people"]:
            entity_parts.append(f"People: {', '.join(sorted(entities_snap['people']))}")
        if entities_snap["decisions"]:
            for d in sorted(entities_snap["decisions"])[-3:]:
                entity_parts.append(f"Decision: {d}")
        if entities_snap["action_items"]:
            for a in sorted(entities_snap["action_items"])[-3:]:
                entity_parts.append(f"Action: {a}")

        has_dynamic = bool(
            summary_text.strip()
            or entity_parts
            or recent_text.strip()
            or screen_text.strip()
            or rag_text.strip()
        )
        if has_dynamic:
            sections.append("=== LIVE CONTEXT (updates during meeting) ===")
            sections.append("")

        if summary_text.strip():
            sections.append("=== MEETING SUMMARY ===")
            sections.append(summary_text)
            sections.append("")

        if entity_parts:
            sections.append("=== TRACKED ENTITIES ===")
            sections.append("\n".join(entity_parts))
            sections.append("")

        if recent_text.strip():
            sections.append("=== RECENT CONVERSATION (last 10 minutes) ===")
            sections.append(recent_text)
            sections.append("")

        if screen_text.strip():
            sections.append("=== SHARED SCREEN CONTENT ===")
            sections.append(screen_text)
            sections.append("")

        if rag_text.strip():
            sections.append("=== PRIMARY SOURCE — use these first ===")
            sections.append(rag_text)

        if not sections:
            return "(Meeting just started — no context available yet.)"

        return "\n".join(sections)

    # ------------------------------------------------------------------
    # Reset
    # ------------------------------------------------------------------

    def flush_remaining_embeddings(self) -> None:
        """Flush all transcript into RAG — including entries still in the raw buffer.

        Called at meeting end. Drains the raw buffer so that the final
        ~5 minutes of conversation are also embedded, not just the
        entries that had already aged out of the buffer window.

        Acquires locks sequentially (raw_buffer lock first, then embed
        lock) and releases each before the slow encoding step.
        """
        # Copy raw buffer entries under its own lock, then release
        with self.raw_buffer._lock:
            remaining = [
                (e["timestamp"], f"{e['speaker']}: {e['text']}")
                for e in self.raw_buffer._entries
            ]

        # Add to embed buffer under embed lock, then release
        if remaining and self.rag_pipeline is not None:
            with self._embed_lock:
                self._transcript_embed_buffer.extend(remaining)

        # Flush calls encoding outside the embed lock internally
        self._flush_embed_buffer(force=True)

    def get_checkpoint_state(self) -> dict[str, Any]:
        """Snapshot current memory state for periodic persistence.

        Returns a serializable dict that can be stored in the DB so
        session recovery after a crash has access to the rolling summary,
        entity tracker, and recent transcript instead of starting from zero.

        Returns:
            Dictionary with summary, entities, and recent buffer text.
        """
        with self._state_lock:
            entities_snap = {k: list(v) for k, v in self._entities.items()}

        summary_text = self.rolling_summary.get_summary()
        key_facts = list(self.rolling_summary._key_facts)

        return {
            "rolling_summary": summary_text,
            "key_facts": key_facts,
            "entities": entities_snap,
            "meeting_id": self.meeting_id,
            "agent_id": self.agent_id,
            "user_id": self.user_id,
        }

    def restore_from_checkpoint(self, checkpoint: dict[str, Any]) -> None:
        """Restore memory state from a checkpoint dict.

        Used during session recovery after a crash/restart to avoid
        losing the rolling summary, entities, and recent context.

        Args:
            checkpoint: Dict from a prior ``get_checkpoint_state()`` call.
        """
        if not checkpoint:
            return
        summary = checkpoint.get("rolling_summary", "")
        if summary:
            self.rolling_summary.summary = summary
        key_facts = checkpoint.get("key_facts", [])
        if key_facts:
            self.rolling_summary._key_facts = key_facts

        entities = checkpoint.get("entities", {})
        if entities:
            with self._state_lock:
                for key in self._entities:
                    if key in entities:
                        self._entities[key] = set(entities[key])

        logger.info(
            "Restored checkpoint for meeting %s: summary=%d chars, %d entities",
            self.meeting_id,
            len(summary),
            sum(len(v) for v in entities.values()) if entities else 0,
        )

    def reset(self) -> None:
        """Clear all context layers.

        Used when resetting between sessions or when the meeting ends.
        Flushes everything (raw buffer + embed buffer) into RAG first,
        then clears all state.
        """
        self.flush_remaining_embeddings()  # drain everything first
        self.rolling_summary.reset()
        self.raw_buffer.clear()
        self.rag_pipeline = None
        with self._state_lock:
            self.document_summaries.clear()
            self._screen_contents.clear()
            self.past_meeting_summaries.clear()
            self._entities = {
                "people": set(),
                "topics": set(),
                "decisions": set(),
                "action_items": set(),
            }
