"""Context assembly manager.

Assembles the optimal context window for each LLM query by combining
rolling transcript summaries, recent raw transcript, RAG-retrieved
document chunks, and optional web search results. Manages token budgets
to stay within model limits.

Phase 3 implementation.
"""

from __future__ import annotations

import asyncio
import logging
import threading
from datetime import datetime, timezone
from typing import Any

from app.context.raw_buffer import RawTranscriptBuffer
from app.context.rolling_summary import RollingSummary

logger = logging.getLogger(__name__)


class ContextManager:
    """Assembles and manages the context window for LLM queries.

    Combines multiple context sources (transcript, documents, search)
    into a single prompt that fits within the model's token budget.

    Attributes:
        max_context_tokens: Maximum tokens allocated for context.
        rolling_summary: The rolling transcript summarizer.
        raw_buffer: The raw transcript buffer.
        rag_pipeline: The RAG retrieval pipeline (``None`` until set).
    """

    def __init__(self, max_context_tokens: int = 16000) -> None:
        """Initialize the context manager and its sub-components.

        Args:
            max_context_tokens: Maximum number of tokens to allocate for
                context in each LLM query. Must leave room for the system
                prompt and model response.
        """
        self.max_context_tokens = max_context_tokens
        self.rolling_summary: RollingSummary = RollingSummary()
        self.raw_buffer: RawTranscriptBuffer = RawTranscriptBuffer(max_minutes=10)
        self.rag_pipeline: Any | None = None
        self.document_summaries: list[dict[str, str]] = []
        self.past_meeting_summaries: list[dict[str, str]] = []
        self._entities: dict[str, set[str]] = {
            "people": set(),
            "topics": set(),
            "decisions": set(),
            "action_items": set(),
        }
        self._transcript_embed_buffer: list[tuple[datetime, str]] = []
        self._embed_chunk_target: int = 200  # words per RAG chunk
        self._embed_stale_seconds: float = 120.0  # force-flush if oldest entry > 2 min
        self._embed_lock = threading.Lock()

    def set_rag_pipeline(self, rag: Any) -> None:
        """Inject the RAG retrieval pipeline.

        Args:
            rag: An object with a ``search(query, top_k)`` method
                (e.g. :class:`~app.context.rag.RAGPipeline`).
        """
        self.rag_pipeline = rag

    def add_document_summary(self, filename: str, summary: str) -> None:
        """Register a document summary for inclusion in context.

        Args:
            filename: Display name of the document.
            summary: Full-document summary generated by the LLM.
        """
        if summary and summary.strip():
            self.document_summaries.append(
                {"filename": filename, "summary": summary}
            )

    def add_past_meeting_summary(self, meeting_date: str, summary: str) -> None:
        """Register a past meeting summary for cross-meeting memory.

        Args:
            meeting_date: Human-readable date/time of the past meeting.
            summary: Summary text from the previous meeting.
        """
        if summary and summary.strip():
            self.past_meeting_summaries.append(
                {"date": meeting_date, "summary": summary}
            )

    def _extract_entities(self, text: str, speaker: str) -> None:
        """Extract entities from transcript text.

        Tracks people (from speaker labels), decisions, and action items
        using fast keyword matching. No LLM call required.

        Args:
            text: The transcript text to scan.
            speaker: Name of the speaker.
        """
        if speaker and speaker.lower() not in ("unknown", "", "bot"):
            self._entities["people"].add(speaker)

        t = text.lower()

        # Decisions
        decision_markers = (
            "we decided", "let's go with", "agreed to",
            "the decision is", "we'll do", "final answer is",
        )
        for marker in decision_markers:
            if marker in t:
                self._entities["decisions"].add(text.strip())
                break

        # Action items
        action_markers = (
            "i will", "i'll", "we need to", "action item",
            "todo", "follow up on", "assigned to",
        )
        for marker in action_markers:
            if marker in t:
                self._entities["action_items"].add(text.strip())
                break

    # ------------------------------------------------------------------
    # Token helpers
    # ------------------------------------------------------------------

    def get_token_count(self, text: str) -> int:
        """Estimate the token count for a text string.

        Uses a fast word-based approximation (words x 1.5) rather than
        a full tokenizer, trading perfect accuracy for zero dependencies.
        The 1.5 multiplier is conservative to avoid overrunning budgets.

        Args:
            text: The text to count tokens for.

        Returns:
            Estimated token count.
        """
        return int(len(text.split()) * 1.5)

    # ------------------------------------------------------------------
    # Transcript ingestion
    # ------------------------------------------------------------------

    def add_transcript(self, text: str, timestamp: datetime | None = None) -> None:
        """Append new transcript text to the raw buffer and rolling summary.

        Collects entries evicted from the raw buffer (both deque overflow
        and time-based pruning) and routes them to the embed buffer so
        they end up in ChromaDB rather than being silently lost.

        Args:
            text: Transcript text segment.
            timestamp: When the segment was captured. Defaults to now.
        """
        # Extract speaker from "Speaker: text" format for entity tracking
        speaker = ""
        if ": " in text:
            parts = text.split(": ", 1)
            candidate = parts[0].strip()
            words = candidate.split()
            if 1 <= len(words) <= 3 and all(w[0].isupper() for w in words if w):
                speaker = candidate

        self._extract_entities(text, speaker)

        # Append to buffer — returns entries evicted by overflow or age
        evicted = self.raw_buffer.append(text, timestamp=timestamp)

        # Route evicted entries into the embed buffer for RAG embedding
        if evicted and self.rag_pipeline is not None:
            with self._embed_lock:
                self._transcript_embed_buffer.extend(evicted)
            self._flush_embed_buffer()

        # RollingSummary.update is async. We schedule it on the running
        # loop when one exists; otherwise the pending text simply
        # accumulates and will be summarized on the next async call.
        try:
            loop = asyncio.get_running_loop()
            task = loop.create_task(self.rolling_summary.update(text))
            task.add_done_callback(
                lambda t: logger.error("Summary update failed: %s", t.exception())
                if not t.cancelled() and t.exception() else None
            )
        except RuntimeError:
            self.rolling_summary.add_pending(text)

    # ------------------------------------------------------------------
    # Context assembly
    # ------------------------------------------------------------------

    def _flush_embed_buffer(self, force: bool = False) -> None:
        """Batch accumulated transcript lines into ~200-word chunks and embed.

        Accumulates short transcript lines until they reach the target
        chunk size, then embeds the combined text into RAG as a single
        paragraph-length chunk for better retrieval quality.

        Extracts data under the embed lock, then releases it before the
        actual encoding call (which is slow) to avoid blocking other
        callers.

        Args:
            force: If True, embed whatever is buffered regardless of size.
        """
        # Extract buffer contents under lock, then release before encoding
        with self._embed_lock:
            if not self._transcript_embed_buffer or self.rag_pipeline is None:
                return

            # Check whether we should flush yet
            combined = " ".join(text for _, text in self._transcript_embed_buffer)
            word_count = len(combined.split())

            if not force and word_count < self._embed_chunk_target:
                oldest_ts = self._transcript_embed_buffer[0][0]
                age = (datetime.now(timezone.utc) - oldest_ts).total_seconds()
                if age < self._embed_stale_seconds:
                    return  # wait for more lines
                force = True  # stale — flush what we have

            # Copy the buffer and clear it while still under lock
            buffer_copy = list(self._transcript_embed_buffer)
            self._transcript_embed_buffer.clear()

        # Build a word-to-entry index for accurate per-chunk timestamps.
        # Each word maps back to the entry it came from, so chunks get
        # the timestamp of their first and last contributing entry.
        entry_words: list[tuple[str, int]] = []  # (word, entry_index)
        for idx, (_, text) in enumerate(buffer_copy):
            for w in text.split():
                entry_words.append((w, idx))

        # Embed in ~200-word chunks with 10% overlap (outside the lock)
        overlap = self._embed_chunk_target // 10
        start = 0

        while start < len(entry_words):
            end = min(start + self._embed_chunk_target, len(entry_words))
            chunk_words = entry_words[start:end]
            chunk_text = " ".join(w for w, _ in chunk_words)

            min_words = 5 if force else 20
            if len(chunk_words) >= min_words:
                first_entry_idx = chunk_words[0][1]
                last_entry_idx = chunk_words[-1][1]
                first_ts = buffer_copy[first_entry_idx][0]
                last_ts = buffer_copy[last_entry_idx][0]
                # Extract unique speakers from the chunk entries
                chunk_entry_indices = set(idx for _, idx in chunk_words)
                speakers_in_chunk = set()
                for ei in chunk_entry_indices:
                    entry_text = buffer_copy[ei][1]
                    # Speaker is the part before first ": "
                    if ": " in entry_text:
                        spk = entry_text.split(": ", 1)[0].strip()
                        if spk:
                            speakers_in_chunk.add(spk)

                try:
                    self.rag_pipeline.add_chunk(
                        text=chunk_text,
                        metadata={
                            "source": "meeting_transcript",
                            "type": "transcript",
                            "speakers": ", ".join(sorted(speakers_in_chunk)) or "unknown",
                            "start_time": first_ts.isoformat(),
                            "end_time": last_ts.isoformat(),
                        },
                    )
                except Exception as exc:
                    logger.warning("Failed to embed transcript chunk: %s", exc)

            if end >= len(entry_words):
                break
            start = end - overlap

    def _rewrite_query(self, question: str, recent_text: str) -> str:
        """Rewrite vague queries by resolving pronouns and references.

        Uses the recent transcript buffer to expand "he", "she", "that",
        "it" into specific names and topics. No LLM call — pure heuristic.

        Args:
            question: The user's raw question.
            recent_text: Recent conversation text from the buffer.

        Returns:
            Rewritten query optimized for RAG search.
        """
        q = question.lower().strip()

        # If question is already specific (contains proper nouns or 5+ words), use as-is
        if len(q.split()) >= 6:
            return question

        # Check if question has vague references that need resolving
        vague_markers = ("he ", "she ", "they ", "him ", "her ", "that ", "this ", "it ",
                         "he?", "she?", "they?", "that?", "this?", "it?",
                         "what did", "who said", "just said", "was saying",
                         " that", " this", " it")
        if not any(m in q for m in vague_markers):
            return question

        # Extract recent speakers and their last statements from buffer
        if not recent_text:
            return question

        lines = recent_text.strip().split("\n")
        recent_speakers: list[tuple[str, str]] = []  # (speaker, text)
        for line in reversed(lines):
            # Format: "[2m ago] Speaker Name: text" or "Speaker Name: text"
            if ": " in line:
                parts = line.split(": ", 1)
                speaker_part = parts[0].strip()
                # Remove timestamp prefix like "[2m ago] "
                if "]" in speaker_part:
                    speaker_part = speaker_part.split("]", 1)[-1].strip()
                if speaker_part and len(speaker_part.split()) <= 4:
                    recent_speakers.append((speaker_part, parts[1].strip()))
                    if len(recent_speakers) >= 5:
                        break

        if not recent_speakers:
            return question

        # Build expanded query
        expanded = question
        people = list(dict.fromkeys(s[0] for s in recent_speakers))  # unique, ordered
        topics = " ".join(s[1][:50] for s in recent_speakers[:3])

        # Replace pronouns with most recent speaker names
        if any(m in q for m in ("he ", "him ", "he?")):
            expanded = f"{question} (referring to {people[0] if people else 'previous speaker'})"
        elif any(m in q for m in ("she ", "her ", "she?")):
            expanded = f"{question} (referring to {people[0] if people else 'previous speaker'})"
        elif any(m in q for m in ("they ", "they?")):
            expanded = f"{question} (referring to {', '.join(people[:2])})"
        elif any(m in q for m in ("that ", "this ", "it ", "that?", "this?", "it?")) or q.endswith(("that", "this", "it")):
            # "that" / "this" / "it" refers to the recent topic
            expanded = f"{question} (context: {topics[:100]})"
        elif "just said" in q or "was saying" in q:
            if recent_speakers:
                expanded = f"{question} ({recent_speakers[0][0]} said: {recent_speakers[0][1][:80]})"

        return expanded

    def _truncate_from_beginning(self, text: str, max_tokens: int) -> str:
        """Truncate *text* from the beginning to fit within *max_tokens*.

        Keeps the most recent content (end of string) which is typically
        the most relevant for meeting context.

        Args:
            text: The source text.
            max_tokens: Token budget for this section.

        Returns:
            The (possibly truncated) text.
        """
        words = text.split()
        # Reverse the approximation: max_tokens / 1.5 ~ max_words
        max_words = int(max_tokens / 1.5)
        if len(words) <= max_words:
            return text
        return " ".join(words[-max_words:])

    def assemble_context(self, question: str, session_id: str) -> str:
        """Build the full context string for an LLM query.

        Assembles context in priority order:
        1. Rolling summary of the full conversation
        2. Recent raw transcript (last ~5 minutes)
        3. RAG-retrieved document chunks relevant to the question

        Token budget allocation (approximate):
        - 20 % meeting summary
        - 30 % recent buffer
        - 20 % document summaries (full-document understanding)
        - 30 % RAG chunks (specific document passages)

        Args:
            question: The user's question, used to guide RAG retrieval.
            session_id: The active meeting session ID for retrieving
                the correct transcript data.

        Returns:
            A formatted context string ready for inclusion in the
            LLM prompt, within the token budget.
        """
        budget_past = int(self.max_context_tokens * 0.10)
        budget_summary = int(self.max_context_tokens * 0.15)
        budget_buffer = int(self.max_context_tokens * 0.25)
        budget_doc_summaries = int(self.max_context_tokens * 0.20)
        budget_rag = int(self.max_context_tokens * 0.30)

        # --- Section 1: Rolling meeting summary ---
        summary_text = self.rolling_summary.get_summary()
        summary_text = self._truncate_from_beginning(summary_text, budget_summary)

        # --- Section 2: Recent raw transcript ---
        recent_text = self.raw_buffer.get_recent(minutes=10)
        recent_text = self._truncate_from_beginning(recent_text, budget_buffer)

        # --- Section 3: Document summaries (full-document understanding) ---
        doc_summary_text = ""
        if self.document_summaries:
            parts = []
            for doc in self.document_summaries:
                parts.append(f"[{doc['filename']}]:\n{doc['summary']}")
            doc_summary_text = "\n\n".join(parts)
        doc_summary_text = self._truncate_from_beginning(
            doc_summary_text, budget_doc_summaries
        )

        # --- Section 4: RAG chunks (specific passages) ---
        # Flush any pending transcript into RAG before searching,
        # so recently-pruned content is findable immediately.
        if self.rag_pipeline is not None:
            self._flush_embed_buffer(force=True)

        # Rewrite vague queries using recent conversation context.
        # Resolves "he", "she", "that", "it" into specific names/topics
        # so RAG search finds the right chunks.
        search_query = self._rewrite_query(question, recent_text)

        rag_text = ""
        if self.rag_pipeline is not None:
            try:
                search_fn = getattr(self.rag_pipeline, "hybrid_search", self.rag_pipeline.search)
                results: list[dict[str, Any]] = search_fn(
                    query=search_query, top_k=8
                )
                chunks: list[str] = []
                for result in results:
                    text_content = result.get("text", "")
                    metadata = result.get("metadata", {})
                    if metadata.get("source") == "meeting_transcript":
                        label = "Earlier in this meeting"
                    else:
                        label = metadata.get("filename", "document")
                    chunks.append(f"[{label}]: {text_content}")
                rag_text = "\n\n".join(chunks)
            except Exception:
                rag_text = ""

        rag_text = self._truncate_from_beginning(rag_text, budget_rag)

        # --- Section 5: Past meeting summaries ---
        past_text = ""
        if self.past_meeting_summaries:
            parts = []
            for pm in self.past_meeting_summaries:
                parts.append(f"[{pm['date']}]:\n{pm['summary']}")
            past_text = "\n\n".join(parts)
        past_text = self._truncate_from_beginning(past_text, budget_past)

        # --- Assemble (skip empty sections to avoid confusing the LLM) ---
        sections: list[str] = []

        if past_text.strip():
            sections.append("=== PAST MEETINGS ===")
            sections.append(past_text)
            sections.append("")

        if summary_text.strip():
            sections.append("=== MEETING SUMMARY ===")
            sections.append(summary_text)
            sections.append("")

        if recent_text.strip():
            sections.append("=== RECENT CONVERSATION (last 5 minutes) ===")
            sections.append(recent_text)
            sections.append("")

        if any(self._entities.values()):
            entity_parts = []
            if self._entities["people"]:
                entity_parts.append(
                    f"People in meeting: {', '.join(sorted(self._entities['people']))}"
                )
            if self._entities["decisions"]:
                recent_decisions = list(self._entities["decisions"])[-5:]
                entity_parts.append(f"Decisions made: {'; '.join(recent_decisions)}")
            if self._entities["action_items"]:
                recent_actions = list(self._entities["action_items"])[-5:]
                entity_parts.append(f"Action items: {'; '.join(recent_actions)}")
            sections.append("=== MEETING ENTITIES ===")
            sections.append("\n".join(entity_parts))
            sections.append("")

        if doc_summary_text.strip():
            sections.append("=== DOCUMENT OVERVIEWS ===")
            sections.append(doc_summary_text)
            sections.append("")

        if rag_text.strip():
            sections.append("=== RELEVANT DOCUMENT PASSAGES (PRIMARY SOURCE — use these first) ===")
            sections.append(rag_text)

        if not sections:
            return "(Meeting just started — no context available yet.)"

        return "\n".join(sections)

    # ------------------------------------------------------------------
    # Reset
    # ------------------------------------------------------------------

    def flush_remaining_embeddings(self) -> None:
        """Flush all transcript into RAG — including entries still in the raw buffer.

        Called at meeting end. Drains the raw buffer so that the final
        ~5 minutes of conversation are also embedded, not just the
        entries that had already aged out of the buffer window.

        Acquires locks sequentially (raw_buffer lock first, then embed
        lock) and releases each before the slow encoding step.
        """
        # Copy raw buffer entries under its own lock, then release
        with self.raw_buffer._lock:
            remaining = [
                (e["timestamp"], f"{e['speaker']}: {e['text']}")
                for e in self.raw_buffer._entries
            ]

        # Add to embed buffer under embed lock, then release
        if remaining and self.rag_pipeline is not None:
            with self._embed_lock:
                self._transcript_embed_buffer.extend(remaining)

        # Flush calls encoding outside the embed lock internally
        self._flush_embed_buffer(force=True)

    def reset(self) -> None:
        """Clear all context layers.

        Used when resetting between sessions or when the meeting ends.
        Flushes everything (raw buffer + embed buffer) into RAG first,
        then clears all state.
        """
        self.flush_remaining_embeddings()  # drain everything first
        self.rolling_summary.reset()
        self.raw_buffer.clear()
        self.rag_pipeline = None
        self.document_summaries.clear()
        self.past_meeting_summaries.clear()
        for v in self._entities.values():
            v.clear()
